name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm globally
      run: |
        npm install -g pnpm
        pnpm --version  # Pastikan pnpm terinstall dengan benar
    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install dependencies with pnpm
      run: pnpm install --frozen-lockfile
    - name: Build the app
      run: pnpm build --if-present
    - name: Debugging: Check working directory and pnpm version
      run: |
        echo "Current working directory: $(pwd)"
        ls -la  # Cek file dan folder
        pnpm --version  # Verifikasi pnpm sudah terinstall
    - name: Run dev command
      run: |
        echo "Running pnpm dev..."
        pnpm dev  # Jalankan dev server
