name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies with npm
      run: npm ci

    - name: Build project (if present)
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        # Version of pnpm to install
        version: '7.x' # Atur versi pnpm yang diinginkan, bisa ganti sesuai keinginan
        # File path to the package.json to read "packageManager" configuration
        package_json_file: 'package.json'

    - name: Install dependencies with pnpm
      run: pnpm install --frozen-lockfile

    - name: Build with pnpm
      run: pnpm run build --if-present

    - name: Run dev command with pnpm
      run: pnpm run dev
